# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: black
        name: Black Code Formatter
        entry: uv run black
        language: system
        types: [python]
        require_serial: true
      - id: isort
        name: isort Import Sorter
        entry: uv run isort
        language: system
        types: [python]
        require_serial: true
      - id: flake8
        name: Flake8 Linter
        entry: uv run flake8
        language: system
        types: [python]
        require_serial: true